name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main  # Runs on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # prevent using the default token

    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy to gh-pages
      run: |
        # Delete the old gh-pages branch if it exists
        git fetch origin gh-pages || echo "no gh-pages yet"
        git branch -D gh-pages || echo "no local gh-pages branch"
        git checkout --orphan gh-pages

        # Remove everything except the site folder
        git rm -rf .

        # Copy the contents of site into root
        cp -r site/* .

        # Commit and push to gh-pages
        git add .
        git commit -m "Deploy site"
        git push -f origin gh-pages
